// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsN8sNgu7IhEZxSv31RZddJCdRJYh1zWY',
    appId: '1:506901322194:web:9c3bf285da818c0860d00b',
    messagingSenderId: '506901322194',
    projectId: 'peppy-strategy-335213',
    authDomain: 'peppy-strategy-335213.firebaseapp.com',
    storageBucket: 'peppy-strategy-335213.appspot.com',
    measurementId: 'G-21ZRTJMEB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Le-COITsQox7bQiN-3YsJSORJWbWeJk',
    appId: '1:506901322194:android:c6802734b87c4b8c60d00b',
    messagingSenderId: '506901322194',
    projectId: 'peppy-strategy-335213',
    storageBucket: 'peppy-strategy-335213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALwbMzPXntc6YNTYpmvPeK-l0iticMnbI',
    appId: '1:506901322194:ios:ab46df046adf585f60d00b',
    messagingSenderId: '506901322194',
    projectId: 'peppy-strategy-335213',
    storageBucket: 'peppy-strategy-335213.appspot.com',
    iosClientId: '506901322194-9non9ej60472bb0ns9gp8p0aiv0hp51p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALwbMzPXntc6YNTYpmvPeK-l0iticMnbI',
    appId: '1:506901322194:ios:0334e82c66a8c85560d00b',
    messagingSenderId: '506901322194',
    projectId: 'peppy-strategy-335213',
    storageBucket: 'peppy-strategy-335213.appspot.com',
    iosClientId: '506901322194-4cu55rfohus0vrbatee1i93oqh6ecogo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
